# Generated by Django 5.0 on 2024-11-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraSecure_app', '0010_alter_data_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='content',
        ),
    ]
