# Generated by Django 5.0 on 2024-11-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraSecure_app', '0011_remove_data_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='content',
            field=models.TextField(max_length=510, null=True),
        ),
    ]
