# Generated by Django 5.0 on 2024-11-09 22:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraSecure_app', '0012_data_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkg_name', models.CharField(max_length=20)),
                ('pkg_price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scr_start_date', models.DateField(default=datetime.date.today)),
                ('scr_end_date', models.DateField(default=datetime.date(2024, 12, 8))),
                ('is_active', models.BooleanField(default=1)),
                ('scr_pkg', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NeuraSecure_app.packages')),
                ('scr_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
