# Generated by Django 5.0 on 2024-11-09 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuraSecure_app', '0013_packages_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribed_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NeuraSecure_app.category')),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='NeuraSecure_app.subscriptions')),
            ],
        ),
    ]
